[package]
name = "carrier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvm-ioctls = "0.11.0"
kvm-bindings = "0.5.0"
libc = "0.2.117"