[package]
name = "kvm"
version = "0.1.0"

[dependencies]
libc = ">=0.2.39"
kvm-ioctls = { version = "0.11.0", path = "../kvm-ioctls" }
kvm-bindings = { version = "0.5.0", path = "../kvm-bindings" }
vmm-sys-util = { version = "0.9.0", path = "../vmm-sys-util" } 